### ISSUE TITLE
"Updating properties" Frame is not closed after apply properties

### ISSUE THREAD

**Issue by jkotan** [tango-controls/jive#47]
Hi,

We have noticed that when we modify more device properties at one time in jive  "Updating properties" Frame is not closed properly.  One can fix it by changing 

     diff --git a/src/main/java/jive3/ProgressFrame.java b/src/main/java/jive3/ProgressFrame.java
    index 1b5adb4..f227088 100644
    --- a/src/main/java/jive3/ProgressFrame.java
    +++ b/src/main/java/jive3/ProgressFrame.java
    @@ -27,7 +27,7 @@ public class ProgressFrame extends JFrame {
       }
     
       static public void hideProgress() {
    -    if(prgFrame!=null) prgFrame.setVisible(false);
    +    if(prgFrame!=null) prgFrame.dispose();
       }
     
       // -------------------------------------------------------

It looks like using `JFrame.dispose()` is recommended (http://stackoverflow.com/questions/24472661/java-gui-using-setvisible)

At DESY we use debian jessie  with gnome.

Best regards,
Jan

**Comment by Ingvord** [comment]
Could you please create a PR?

**Comment by Ingvord** [comment]
Great! Thanks a lot for the PR!

**Comment by Ingvord** [comment]
I guess this one can be now closed. Reason: #48  has been merged
