### ISSUE TITLE
Jive does not support full range of DevULong64 values

### ISSUE THREAD

**Issue by t-b** [tango-controls/jive#52]
Tango 9.2.5a and TangoTest device

In Jive i can not set `ulong64_scalar` to values like 2^64 - 1. The largest value I can set is 2^63-1. Additionally values like `-1` are accepted where as `ulong_scalar` does not accept negative values.

**Comment by JeanLucPons** [comment]
Java does not handle unsigned 64 bits.
To handle this properly we should use BigInt but this requires modifications in the Tango java API.
