### ISSUE TITLE
Check Property file fails if an attribute property doesn't exists in database

### ISSUE THREAD

**Issue by abdomit** [tango-controls/jive#54]
Got a "NullPointerException" error message when checking an property file which have an attribute property not defined in the database.

For instance the following line in the property file will lead to an error if format is the default one:

my/beautiful/device/my_attribute->format: %4.3f

**Comment by abdomit** [comment]
Sometimes it works, but I couldn't figured out what triggers this error message...

**Comment by JeanLucPons** [comment]
Fixed in Jive 7.20

**Comment by abdomit** [comment]
Thanks!
